import starlight from '@astrojs/starlight';
import { defineConfig } from 'astro/config';

// QAuth documentation site (docs.qauth.dev), #347.
export default defineConfig({
  site: 'https://docs.qauth.dev',
  output: 'static',
  // Astro's default `outDir` is `./dist` relative to this project. Nx's
  // `build` target (project.json) declares its output as the
  // workspace-level `dist/apps/docs-site`, so `outDir` is redirected here to
  // match — a declared Nx output that does not match reality breaks caching
  // silently.
  outDir: '../../dist/apps/docs-site',
  integrations: [
    starlight({
      title: 'QAuth',
      // Five lanes, each entirely autogenerated from its directory. Do not
      // enumerate pages by hand: four content tasks land in parallel
      // branches, and a hand-maintained page list here would make this file
      // a merge-conflict choke point for every one of them. Adding a page
      // to a lane directory is enough to make it appear in the sidebar; a
      // page's position within its lane comes from its own
      // `sidebar.order` frontmatter (see extend/frontmatter.md).
      sidebar: [
        { label: 'Integrate', items: [{ autogenerate: { directory: 'integrate' } }] },
        { label: 'Operate', items: [{ autogenerate: { directory: 'operate' } }] },
        { label: 'Extend', items: [{ autogenerate: { directory: 'extend' } }] },
        { label: 'Portal & Dashboard', items: [{ autogenerate: { directory: 'portal' } }] },
        { label: 'Reference', items: [{ autogenerate: { directory: 'reference' } }] },
      ],
    }),
  ],
});
