import starlight from '@astrojs/starlight';
import { defineConfig } from 'astro/config';

import { GITHUB_REPO_BLOB_BASE } from './src/lib/records.ts';
import { resolveRepoRoot } from './src/lib/repo-root.ts';
import { remarkRewriteRecordLinks } from './src/plugins/remark-rewrite-record-links.ts';

// QAuth documentation site (docs.qauth.dev), #347.
export default defineConfig({
  site: 'https://docs.qauth.dev',
  output: 'static',
  // Astro's default `outDir` is `./dist` relative to this project. Nx's
  // `build` target (project.json) declares its output as the
  // workspace-level `dist/apps/docs-site`, so `outDir` is redirected here to
  // match — a declared Nx output that does not match reality breaks caching
  // silently.
  outDir: '../../dist/apps/docs-site',
  markdown: {
    // Task 10 (#356): rewrites the relative `.md` links inside the
    // rendered records (docs/adr/*.md, docs/security/*.md) into working
    // site routes at build time — see the plugin's own doc comment. Global
    // rather than scoped to the `records` collection: Astro applies
    // `markdown.remarkPlugins` to every collection's markdown/MDX (`docs`
    // included). `docs` pages DO link to un-rendered repo files today, but
    // with a different, repo-root-ABSOLUTE convention (`/docs/agent-authorization.md`,
    // not `./` or `../`) that this plugin explicitly leaves alone (see its
    // bucket 0) — no page in `docs` has a RELATIVE `.md` link for it to
    // touch instead (verified — see the Task 10 report), so this is a true
    // no-op there today and stays correct if that ever changes.
    remarkPlugins: [
      [
        remarkRewriteRecordLinks,
        { repoRoot: resolveRepoRoot(), githubBlobBaseUrl: GITHUB_REPO_BLOB_BASE },
      ],
    ],
  },
  integrations: [
    starlight({
      title: 'QAuth',
      // Five lanes, each entirely autogenerated from its directory. Do not
      // enumerate pages by hand: four content tasks land in parallel
      // branches, and a hand-maintained page list here would make this file
      // a merge-conflict choke point for every one of them. Adding a page
      // to a lane directory is enough to make it appear in the sidebar; a
      // page's position within its lane comes from its own
      // `sidebar.order` frontmatter (see extend/frontmatter.md).
      sidebar: [
        { label: 'Integrate', items: [{ autogenerate: { directory: 'integrate' } }] },
        { label: 'Operate', items: [{ autogenerate: { directory: 'operate' } }] },
        { label: 'Extend', items: [{ autogenerate: { directory: 'extend' } }] },
        { label: 'Portal & Dashboard', items: [{ autogenerate: { directory: 'portal' } }] },
        { label: 'Reference', items: [{ autogenerate: { directory: 'reference' } }] },
      ],
    }),
  ],
});
