import { existsSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';

import { recordRouteForRepoPath } from '../lib/records';

/**
 * Rewrites the relative, in-tree `.md` links inside the rendered records
 * (`docs/adr/*.md`, `docs/security/*.md`) — `./007-mcp-first-positioning.md`,
 * `../adr/005-pqc-hybrid-signing.md`, `../eudi-regulatory-drift-log.md#...`
 * — into working links at BUILD TIME, since those relative paths resolve
 * correctly on GitHub (where the records are also read) but 404 as site
 * routes once rendered under `/reference/records/**`.
 *
 * A link falls into exactly one of four buckets:
 *
 *   1. Not an in-tree markdown link at all — an absolute URL with a scheme
 *      (`https://`, `mailto:`, ...) or a bare same-page `#anchor`. Left
 *      completely untouched; these already work wherever the page renders.
 *   2. A relative link whose target IS one of the files the `records`
 *      collection loads (`content.config.ts`) — rewritten to that record's
 *      site route via `recordRouteForRepoPath`. A `#fragment` on the link
 *      survives the rewrite unchanged: this project's heading anchors are
 *      generated by `github-slugger` on both GitHub and (via
 *      `@astrojs/markdown-remark`, which depends on the same package) this
 *      site, so the same fragment string is valid in both places.
 *   3. A relative link whose target is a real repository file but NOT one
 *      the `records` collection loads (e.g. `../../MVP-PRD.md`,
 *      `../eudi-regulatory-drift-log.md`) — rewritten to a GitHub blob URL.
 *      Leaving it as a site-relative path would be worse than useless: on
 *      GitHub `../eudi-regulatory-drift-log.md` resolves correctly relative
 *      to the FILE, but once rendered at `/reference/records/adr/...`, a
 *      browser resolves that same relative path against the PAGE'S URL and
 *      lands nowhere real. A GitHub blob link is a real, working page in
 *      both reading contexts and doesn't invent a site route that doesn't
 *      exist — see the Task 10 report for the full reasoning.
 *   4. A relative `.md` link that resolves to nothing on disk. Left
 *      untouched rather than guessed at; this project has no such link
 *      today (see the plugin's own test suite, which processes every link
 *      extracted from the real `docs/adr` and `docs/security` trees), but a
 *      guess here would be worse than leaving a pre-existing typo exactly
 *      as authored.
 */
export interface RemarkRewriteRecordLinksOptions {
  /** Absolute path to the repository root, for resolving relative links and repo-relative fallbacks. */
  repoRoot: string;
  /** e.g. `https://github.com/qauth-labs/qauth/blob/main` — no trailing slash. */
  githubBlobBaseUrl: string;
}

/**
 * The minimal shapes this plugin actually touches from an mdast tree —
 * `type`, `url`, and `children`. Not importing `mdast`/`unist-util-visit`:
 * neither is a declared dependency of `apps/docs-site` (pnpm's strict
 * linking means only declared dependencies resolve, and the whole `unified`
 * ecosystem here is a nested dependency of `astro`/`@astrojs/markdown-remark`,
 * not something this project imports directly elsewhere), and a hand-rolled
 * walk over `children` is all a link-only transform needs.
 */
export interface MinimalTreeNode {
  type: string;
  url?: string;
  children?: MinimalTreeNode[];
}

export interface MinimalVFile {
  /** Absolute path to the file being processed, as Astro's markdown pipeline sets it. */
  path?: string;
  history?: string[];
}

const SCHEME_RE = /^[a-z][a-z0-9+.-]*:/i;

function splitFragment(url: string): { pathPart: string; fragment: string } {
  const hashIndex = url.indexOf('#');
  if (hashIndex === -1) return { pathPart: url, fragment: '' };
  return { pathPart: url.slice(0, hashIndex), fragment: url.slice(hashIndex) };
}

function visitLinks(node: MinimalTreeNode, visit: (link: MinimalTreeNode) => void): void {
  if (node.type === 'link' && typeof node.url === 'string') {
    visit(node);
  }
  if (Array.isArray(node.children)) {
    for (const child of node.children) visitLinks(child, visit);
  }
}

/** Rewrite a single link's URL in place; returns nothing (bucket 1 and 4 leave `link.url` as-is). */
export function rewriteRecordLink(
  link: MinimalTreeNode,
  sourcePath: string,
  options: RemarkRewriteRecordLinksOptions
): void {
  const url = link.url;
  if (typeof url !== 'string') return;
  if (url.startsWith('#')) return; // bucket 1: bare same-page anchor
  if (SCHEME_RE.test(url)) return; // bucket 1: external (https:, mailto:, tel:, ...)

  const { pathPart, fragment } = splitFragment(url);
  if (!pathPart.endsWith('.md')) return; // not an in-tree markdown link this plugin handles

  const absoluteTarget = resolve(dirname(sourcePath), pathPart);
  if (!existsSync(absoluteTarget)) return; // bucket 4: doesn't resolve to anything real

  const repoRelative = relative(options.repoRoot, absoluteTarget).replace(/\\/g, '/');

  // `recordRouteForRepoPath` is pure path-shape matching (docs/adr/*.md,
  // docs/security/*.md) — checking existence FIRST, above, is what keeps a
  // link that merely LOOKS like a record path (e.g. a typo'd filename that
  // doesn't exist) from bucket 2 rather than correctly falling to bucket 4.
  const route = recordRouteForRepoPath(repoRelative);
  if (route) {
    link.url = `${route}${fragment}`; // bucket 2
    return;
  }

  link.url = `${options.githubBlobBaseUrl}/${repoRelative}${fragment}`; // bucket 3
}

/**
 * The remark plugin (a unified "attacher"): call with options, register the
 * returned transformer via `markdown.remarkPlugins` in `astro.config.mjs`.
 */
export function remarkRewriteRecordLinks(options: RemarkRewriteRecordLinksOptions) {
  return (tree: MinimalTreeNode, file: MinimalVFile) => {
    const sourcePath = file.path ?? file.history?.[0];
    if (!sourcePath) return;
    visitLinks(tree, (link) => rewriteRecordLink(link, sourcePath, options));
  };
}
