import { existsSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';

import { recordRouteForRepoPath } from '../lib/records';

/**
 * Rewrites the relative, in-tree `.md` links inside the rendered records
 * (`docs/adr/*.md`, `docs/security/*.md`) — `./007-mcp-first-positioning.md`,
 * `../adr/005-pqc-hybrid-signing.md`, `../eudi-regulatory-drift-log.md#...`
 * — into working links at BUILD TIME, since those relative paths resolve
 * correctly on GitHub (where the records are also read) but 404 as site
 * routes once rendered under `/reference/records/**`.
 *
 * Registered globally (`astro.config.mjs`'s `markdown.remarkPlugins`), so
 * this also runs over every page in the `docs` collection, not only
 * records. Those pages link to un-rendered repo files with a DIFFERENT,
 * pre-existing convention: repo-root-ABSOLUTE paths like
 * `/docs/agent-authorization.md` (see `integrate/api-reference.md`,
 * `operate/keys.md`, and others). This plugin deliberately leaves that
 * form alone (see bucket 0 below) rather than resolving it — that
 * convention is `link-resolution.ts`'s to interpret (it treats a leading
 * `/` as repo-root-relative, `join(repoRoot, pathPart)`), and is out of
 * scope for Task 10, which only asked for the records' OWN relative links.
 *
 * A link falls into exactly one of six buckets, checked in this order:
 *
 *   0. Repo-root-ABSOLUTE (`pathPart` starts with `/`) — e.g.
 *      `/docs/agent-authorization.md`. Left untouched, by an explicit rule,
 *      not by an accident of path resolution: `path.resolve()` on an
 *      absolute second argument discards the first and resolves against
 *      the filesystem root, which happens to not exist on this machine
 *      either — but relying on that instead of stating the rule would make
 *      the outcome depend on `path.resolve`'s platform semantics rather
 *      than on this plugin's own intent. See this bucket's regression test.
 *   1. Not an in-tree markdown link at all — an absolute URL with a scheme
 *      (`https://`, `mailto:`, ...) or a bare same-page `#anchor`. Left
 *      completely untouched; these already work wherever the page renders.
 *   2. A relative link whose target IS one of the files the `records`
 *      collection loads (`content.config.ts`) — rewritten to that record's
 *      site route via `recordRouteForRepoPath`. A `#fragment` on the link
 *      survives the rewrite unchanged: this project's heading anchors are
 *      generated by `github-slugger` on both GitHub and (via
 *      `@astrojs/markdown-remark`, which depends on the same package) this
 *      site, so the same fragment string is valid in both places.
 *   2b. A relative link whose target is another page of THIS SITE's `docs`
 *      collection (`apps/docs-site/src/content/docs/**`) — rewritten to the
 *      route Starlight serves that page at. Numbered `2b` rather than
 *      renumbering the buckets below, which are referred to by number from
 *      `astro.config.mjs`, `link-resolution.ts`, and this plugin's tests.
 *      Without this bucket the link falls to bucket 3 and a link BETWEEN TWO
 *      SITE PAGES becomes a GitHub blob URL — the reader is silently ejected
 *      out of the rendered docs into raw markdown source. Rewritten rather
 *      than left untouched because nothing else would fix it: Astro and
 *      Starlight do not resolve a relative `.md` link to its page route (no
 *      such remark/rehype step is registered in `astro.config.mjs`), so
 *      `./frontmatter.md` on the rendered page `/extend/architecture/`
 *      resolves in the browser against the PAGE'S URL and 404s — the exact
 *      failure bucket 3 exists to avoid. The rewrite is build-time only, so
 *      the source file keeps the relative form that works when the page is
 *      read on GitHub. No page carries such a link today (verified across
 *      `src/content/docs`), so this is currently a no-op — which is the
 *      point: it makes the plugin's global registration correct for the
 *      first relative link someone writes, not just harmless.
 *   3. A relative link whose target is a real repository file but NOT one
 *      the `records` collection loads (e.g. `../../MVP-PRD.md`,
 *      `../eudi-regulatory-drift-log.md`) — rewritten to a GitHub blob URL.
 *      Leaving it as a site-relative path would be worse than useless: on
 *      GitHub `../eudi-regulatory-drift-log.md` resolves correctly relative
 *      to the FILE, but once rendered at `/reference/records/adr/...`, a
 *      browser resolves that same relative path against the PAGE'S URL and
 *      lands nowhere real. A GitHub blob link is a real, working page in
 *      both reading contexts and doesn't invent a site route that doesn't
 *      exist — see the Task 10 report for the full reasoning.
 *   4. A relative `.md` link that resolves to nothing on disk. Left
 *      untouched rather than guessed at; this project has no such link
 *      today (see the plugin's own test suite, which processes every link
 *      extracted from the real `docs/adr` and `docs/security` trees), but a
 *      guess here would be worse than leaving a pre-existing typo exactly
 *      as authored.
 */
export interface RemarkRewriteRecordLinksOptions {
  /** Absolute path to the repository root, for resolving relative links and repo-relative fallbacks. */
  repoRoot: string;
  /** e.g. `https://github.com/qauth-labs/qauth/blob/main` — no trailing slash. */
  githubBlobBaseUrl: string;
}

/**
 * The minimal shapes this plugin actually touches from an mdast tree —
 * `type`, `url`, and `children`. Not importing `mdast`/`unist-util-visit`:
 * neither is a declared dependency of `apps/docs-site` (pnpm's strict
 * linking means only declared dependencies resolve, and the whole `unified`
 * ecosystem here is a nested dependency of `astro`/`@astrojs/markdown-remark`,
 * not something this project imports directly elsewhere), and a hand-rolled
 * walk over `children` is all a link-only transform needs.
 */
export interface MinimalTreeNode {
  type: string;
  url?: string;
  children?: MinimalTreeNode[];
}

export interface MinimalVFile {
  /** Absolute path to the file being processed, as Astro's markdown pipeline sets it. */
  path?: string;
  history?: string[];
}

const SCHEME_RE = /^[a-z][a-z0-9+.-]*:/i;

function splitFragment(url: string): { pathPart: string; fragment: string } {
  const hashIndex = url.indexOf('#');
  if (hashIndex === -1) return { pathPart: url, fragment: '' };
  return { pathPart: url.slice(0, hashIndex), fragment: url.slice(hashIndex) };
}

/**
 * Where Starlight's `docs` collection lives, repo-relative. Hard-wired to
 * this path by `docsLoader()` itself, not a choice this project makes (see
 * `content.config.ts`'s note quoting the loader: "We still rely on the
 * content collection folder structure to be fixed for now"), so a target
 * under it is a page the site SERVES, not a repo file to link out to.
 */
const CONTENT_DOCS_PREFIX = 'apps/docs-site/src/content/docs/';

/**
 * The route Starlight serves a `docs` collection source file at — `index`
 * segments collapse, every route is trailing-slashed — or `undefined` if the
 * path is not in that collection at all.
 *
 * Deliberately a small duplicate of `src/invariants/content-tree.ts`'s
 * `slugToRoute` rather than an import of it: this project keeps
 * site-rendering code and drift-guard code independent in both directions
 * (see `src/lib/repo-root.ts`'s own comment for the same call), and
 * `content-tree.ts` additionally pulls in `github-slugger`, a devDependency
 * that has no business in the production build graph.
 *
 * Only `.md` reaches here — the caller returns early on anything else — so
 * the `.mdx` pages (`index.mdx`, `reference/records.mdx`,
 * `reference/status.mdx`) are simply never candidates.
 */
function contentDocsRoute(repoRelativePath: string): string | undefined {
  if (!repoRelativePath.startsWith(CONTENT_DOCS_PREFIX)) return undefined;
  const segments = repoRelativePath
    .slice(CONTENT_DOCS_PREFIX.length)
    .replace(/\.md$/, '')
    .split('/');
  if (segments[segments.length - 1] === 'index') segments.pop();
  const route = segments.join('/');
  return route ? `/${route}/` : '/';
}

function visitLinks(node: MinimalTreeNode, visit: (link: MinimalTreeNode) => void): void {
  if (node.type === 'link' && typeof node.url === 'string') {
    visit(node);
  }
  if (Array.isArray(node.children)) {
    for (const child of node.children) visitLinks(child, visit);
  }
}

/** Rewrite a single link's URL in place; returns nothing (buckets 0, 1, and 4 leave `link.url` as-is). */
export function rewriteRecordLink(
  link: MinimalTreeNode,
  sourcePath: string,
  options: RemarkRewriteRecordLinksOptions
): void {
  const url = link.url;
  if (typeof url !== 'string') return;
  if (url.startsWith('#')) return; // bucket 1: bare same-page anchor
  if (SCHEME_RE.test(url)) return; // bucket 1: external (https:, mailto:, tel:, ...)

  const { pathPart, fragment } = splitFragment(url);
  if (!pathPart.endsWith('.md')) return; // not an in-tree markdown link this plugin handles

  // Bucket 0: repo-root-absolute (`/docs/...`) — a different, pre-existing
  // convention this plugin does not touch. Checked explicitly, ahead of
  // `resolve()`, so the outcome is this plugin's stated rule rather than
  // `path.resolve`'s own (platform-dependent) handling of an absolute
  // second argument. See the module doc comment.
  if (pathPart.startsWith('/')) return;

  const absoluteTarget = resolve(dirname(sourcePath), pathPart);
  if (!existsSync(absoluteTarget)) return; // bucket 4: doesn't resolve to anything real

  const repoRelative = relative(options.repoRoot, absoluteTarget).replace(/\\/g, '/');

  // `recordRouteForRepoPath` is pure path-shape matching (docs/adr/*.md,
  // docs/security/*.md) — checking existence FIRST, above, is what keeps a
  // link that merely LOOKS like a record path (e.g. a typo'd filename that
  // doesn't exist) from bucket 2 rather than correctly falling to bucket 4.
  const route = recordRouteForRepoPath(repoRelative);
  if (route) {
    link.url = `${route}${fragment}`; // bucket 2
    return;
  }

  // Bucket 2b: the target is another page of this site's own `docs`
  // collection. Checked BEFORE the blob fallback: a link between two site
  // pages must land on the served route, never on raw source. See the
  // module doc comment for why it is rewritten rather than left for
  // Astro/Starlight, which does not resolve relative `.md` links.
  const contentRoute = contentDocsRoute(repoRelative);
  if (contentRoute) {
    link.url = `${contentRoute}${fragment}`; // bucket 2b
    return;
  }

  link.url = `${options.githubBlobBaseUrl}/${repoRelative}${fragment}`; // bucket 3
}

/**
 * The remark plugin (a unified "attacher"): call with options, register the
 * returned transformer via `markdown.remarkPlugins` in `astro.config.mjs`.
 */
export function remarkRewriteRecordLinks(options: RemarkRewriteRecordLinksOptions) {
  return (tree: MinimalTreeNode, file: MinimalVFile) => {
    const sourcePath = file.path ?? file.history?.[0];
    if (!sourcePath) return;
    visitLinks(tree, (link) => rewriteRecordLink(link, sourcePath, options));
  };
}
