/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsentsRouteImport } from './routes/consents'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedClientsIndexRouteImport } from './routes/_authed/clients.index'
import { Route as AuthedClientsNewRouteImport } from './routes/_authed/clients.new'
import { Route as AuthedClientsClientIdRouteImport } from './routes/_authed/clients.$clientId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentsRoute = ConsentsRouteImport.update({
  id: '/consents',
  path: '/consents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsIndexRoute = AuthedClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsNewRoute = AuthedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsClientIdRoute = AuthedClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consents': typeof ConsentsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/clients/$clientId': typeof AuthedClientsClientIdRoute
  '/clients/new': typeof AuthedClientsNewRoute
  '/clients/': typeof AuthedClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consents': typeof ConsentsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/clients/$clientId': typeof AuthedClientsClientIdRoute
  '/clients/new': typeof AuthedClientsNewRoute
  '/clients': typeof AuthedClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/consents': typeof ConsentsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/clients/$clientId': typeof AuthedClientsClientIdRoute
  '/_authed/clients/new': typeof AuthedClientsNewRoute
  '/_authed/clients/': typeof AuthedClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consents'
    | '/login'
    | '/register'
    | '/verify'
    | '/dashboard'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consents'
    | '/login'
    | '/register'
    | '/verify'
    | '/dashboard'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/consents'
    | '/login'
    | '/register'
    | '/verify'
    | '/_authed/dashboard'
    | '/_authed/clients/$clientId'
    | '/_authed/clients/new'
    | '/_authed/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ConsentsRoute: typeof ConsentsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consents': {
      id: '/consents'
      path: '/consents'
      fullPath: '/consents'
      preLoaderRoute: typeof ConsentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/': {
      id: '/_authed/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthedClientsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/new': {
      id: '/_authed/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthedClientsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/$clientId': {
      id: '/_authed/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthedClientsClientIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedClientsClientIdRoute: typeof AuthedClientsClientIdRoute
  AuthedClientsNewRoute: typeof AuthedClientsNewRoute
  AuthedClientsIndexRoute: typeof AuthedClientsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedClientsClientIdRoute: AuthedClientsClientIdRoute,
  AuthedClientsNewRoute: AuthedClientsNewRoute,
  AuthedClientsIndexRoute: AuthedClientsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ConsentsRoute: ConsentsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
